#!/bin/bash
app=ezpublish

# Retrieve arguments
domain=$(sudo yunohost app setting $app domain)
path=$(sudo yunohost app setting $app path)
admin=$(sudo yunohost app setting $app admin)
is_public=$(sudo yunohost app setting $app is_public)

# Remove database
db_user=ezpublish
db_name=ezpublish
root_pwd=$(sudo cat /etc/yunohost/mysql)

mysql -u root -p$root_pwd -e "DROP DATABASE $db_name ; DROP USER $db_user@localhost ;"

# Remove sources
sudo rm -rf /var/www/$app

# Remove configuration files
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf
sudo rm -f /etc/php5/fpm/pool.d/$app.conf


# Restart services
sudo service nginx reload
sudo service php5-fpm restart
sudo userdel $app > /dev/null 2>&1
sudo yunohost app ssowatconf
